# Site settings
title: epilogos
email: meuleman@mit.edu
description: analysis and visualization of multi-epigenome datasets
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
